### ISSUE TITLE
我在利用OnGUI函数绘制文本框UI的时候遇到问题

### ISSUE THREAD

**Issue by linhaiwen** [3DMXM/wiki.aoe.top#1]
因为OnGUI是不断刷新的，所以我的文本框一旦输入数字就会立刻因为刷新而回归默认状态。
并且文本框不断读取也容易导致软件卡死。
大哥，我这个应该怎么办才能解决。

**Comment by 3DMXM** [comment]
文本框传递的需要是一个变量（可读可写），

**Comment by 3DMXM** [comment]
至于每帧执行会影响性能的问题，你可以使用我后面写的一个UI: [UnityGameUI](https://github.com/GlossMod/UnityGameUI)

一些相关的示例: https://github.com/GlossMod/UnityScriptTrainer | https://github.com/jim972329667/UnityScriptTrainer
